version: "3.9"
services:
  postgresql:
    image: "postgres:14.5"
    volumes:
      - pgdata:/data/postgresql/data
    environment:
      POSTGRES_USER: sqr
      POSTGRES_PASSWORD: sqr
      POSTGRES_DB: sqr_development
    ports:
      - "5432:5432"
  redis:
    image: "redis:7.0.5"
    ports:
      - "6379:6379"
volumes:
  pgdata:
